Lims 229 adding more columns
bikalims/bika.extras pull request #5
Opened 2024-03-14 14:05 UTC by DanE417

## Description of the issue/feature this PR addresses

Linked issue: https://bika.atlassian.net/browse/LIMS-229

## Current behavior before PR
No Asset Number column on Instrument listing

## Desired behavior after PR is merged
To add Asset Number column on Instrument listing

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-03-18 07:04 UTC, luthando5 commented
Hey @DanE417 looking very good! Are you planning on making a new branch for each listing change or is this PR not ready for review yet?

2024-03-18 09:51 UTC, luthando5 commented on src/bika/extras/browser/listingview/samples.py
> +            item["replace"]["Specification"] =spec_link
So far so good :+1:

2024-04-24 05:34 UTC, luthando5 commented on src/bika/extras/browser/overrides/overrides.zcml
Hopefully there will be a fix for this before this PR is ready for review.

2024-04-24 11:10 UTC, DanE417 commented
This does not include LIMS-822 and LIMS-823

2024-04-26 10:22 UTC, luthando5 requested changes

2024-04-26 10:22 UTC, luthando5 commented on src/bika/extras/browser/listingview/analysisservices.py
> +    def folder_item(self, obj, item, index):
We use the replace when we are adding a link to the value. Please remove them if not adding links.

2024-04-26 10:22 UTC, luthando5 commented on src/bika/extras/browser/listingview/bika_analysisprofiles.py
> +        item["replace"]["UsePrice"] = use_price_value
Remove the replace please :)

2024-04-26 10:22 UTC, luthando5 commented on src/bika/extras/browser/listingview/sampletemplates.py
> +        item["replace"]["Composite"] = composite_value
Remove replace please.

2024-04-26 10:25 UTC, luthando5 commented on src/bika/extras/browser/listingview/sampletemplates.py
> +            item["replace"]["SampleTypeTitle    "] = sample_type_link
Remove extra spaces please.

2024-04-26 11:29 UTC, luthando5 commented
Well done on your first PR @DanE417 :1st_place_medal:

2024-04-26 11:30 UTC, luthando5 approved these changes

2024-04-26 11:31 UTC, merged